### ISSUE TITLE
[KPI00,KPI80,KPI81] No sale los parámetros de fechas inicio, frecuencia

### ISSUE THREAD

**Issue by pafmon** [isa-group/governify-project-sas#31]
"En el KPI SPU_IO_K00 no sale los parámetros de fecha inicio, frecuencia, etc"

**Comment by pafmon** [comment]
Solución propuesta: "Meter como meta información de la métrica todos los aspectos que aparecen en la ficha: 
- Fecia Inicio
- Frecuencia
- Ciclo
- Clase
- Tipo: 
  ...

**Comment by feserafim** [comment]
Solución: había que poner 'metadata' en el contrato.
