### ISSUE TITLE
[K80,K81] Población vacía

### ISSUE THREAD

**Issue by feserafim** [isa-group/governify-project-sas#36]
> ---------- Mensaje reenviado ----------
> De: "Carlos Angel Moreno Cordero" c.moreno.cordero@avanade.com
> Fecha: 20 jul. 2016 10:12
> Asunto: RE: Ficheros del Core
>  Para los KPIs 80/81, el campo población es siempre vacío

**Comment by feserafim** [comment]
> ---------- Mensaje reenviado ----------
De: "Manuel Resinas" <resinas@us.es>
Fecha: 20 jul. 2016 11:10
Asunto: Re: Ficheros del Core
[...] el KPI 18 es un poco particular porque el valor objetivo depende del valor de Nodo ETC (si es < 20 y si es >=20) de manera que la única forma en la que hemos podido representar esta casuística es ponerla como si fuese un ámbito más [...]

## Por ejemplo:

Objetivo en K01:
* Prioridad Muy Alta - Mayor o igual al 95%
* Prioridad Alta - Mayor o igual al 90%
* Prioridad Normal - Mayor o igual al 82,5%

Objetivo en K18:
* Nodo < 20 ETCs - Menor o igual a 1
* Nodo >= 20 ETCs - Menor o igual a 2

**Comment by feserafim** [comment]
> ---------- Mensaje reenviado ----------
> De: "Manuel Resinas" resinas@us.es
> Fecha: 20 jul. 2016 11:10
> Asunto: Re: Ficheros del Core
> [...] lo que ocurre es que el valor es precisamente la población y las ocurrencias por la forma en la que está definido el KPI. Lo mismo ocurre con el campo ocurrencia. En cualquier caso, lo corregimos.

**Comment by pafmon** [comment]
Solución (en reporter): 
- Ambos campos (población y ocurrencias) deben tener lo mismo que el campo valor en el caso del K80 y K81. 
- Para K00 y K06_C, los campos (población y ocurrencias) deben valer 0
