### ISSUE TITLE
Cambiar K18 a period quarterly en vez de monthly

### ISSUE THREAD

**Issue by antgamdia** [isa-group/governify-project-sas#43]

**Comment by pafmon** [comment]
Hay que realizar las siguientes acciones: 
- [x] En PPINOT se debe tener en cuenta el period (monthly,...) y el "initial" completo (no sólo el día)
- [x] En el pricing billing, tener en cuenta los distintos tipos de periodo y solo sumar en el "to" del periodo (día de la fecha).

**Comment by pafmon** [comment]
Revisar: 
ene-feb-mar 

Ind,   Fact, Inicio, Fin
K18 , 201501, 2014-10-15 , 2015-01-15

**Comment by juanludlf** [comment]
Reporter debe devolver en kpis lo siguiente (simplificacion de salida):
  KPI, factura, inicio, fin, valor
   K18, 201501,  2014-10-15, 2015-01-15, YY
   K00, 201411,  2014-10-15, 2014-11-15, XX  // no suma K18
   K00, 201412,  2014-11-15, 2014-12-15, XX // no suma K18
   K00, 201501,  2014-12-15, 2015-01-15, XX+YY   // SI suma K18
