### ISSUE TITLE
Pasar la llamada al reload desde el log de frontend a backend

### ISSUE THREAD

**Issue by juanludlf** [isa-group/governify-project-sas#52]
Actualmente se envía desde frontend sin esperar al procesamiento de los logs, y habría que pasarla al backend para que se haga la llamada al reload justo después de enviar el correo: v1.js (l:125, exports.POST_loader)

**Comment by antgamdia** [comment]
Resuelto en 02ad06e9e0345da0659fdea29cc610a4a925de1b (tests pendientes)
