### ISSUE TITLE
Corregir valores de los campos "línea" y "actividad" con los valores de la ficha

### ISSUE THREAD

**Issue by feserafim** [isa-group/governify-project-sas#56]
> En todas los registros, la linea y la actividad no corresponde con la ficha. Las fichas dice:
> -Línea: Línea de servicio de operación
> -Actividad:Actividad no planificada

**Comment by pafmon** [comment]
Solucion: hay que modificar el SLA

**Comment by feserafim** [comment]
Solución: actualizar campos `context.definitions.scopes.SPU.(serviceLine/activity)` del contrato.
