### ISSUE TITLE
[K10] KPI con valor en "COMPENSACIONUND" y sin valor en "COMPENSACION"

### ISSUE THREAD

**Issue by feserafim** [isa-group/governify-project-sas#58]
> Para mayo'16, el kpi 10, para P1 y SEVILLA, el valor es 4,76; luego tendría que tener compensación calculada ya que no cumple el objetivo.

**Comment by juanludlf** [comment]
Solución: en el contrato, los umbrales de las condiciones de penalización eran erróneos
