### ISSUE TITLE
[K05] No tiene valor para el campo TIEMPO

### ISSUE THREAD

**Issue by feserafim** [isa-group/governify-project-sas#59]
> La incidencia 3567254 unas veces tiene el TIEMPO informado y otras no.

**Comment by pafmon** [comment]
Solucion: poner una evidencia K05_issue_duration  nueva especifica para el K05 que sustituria issue_duration .

"K05_issue_duration" contaria el tiempo que pasan abiertas sin contar prioridad.

**Comment by juanludlf** [comment]
K18 también

**Comment by feserafim** [comment]
- [x] Crear la nueva evidencia y actualizarla en designer.
- [x] Actualizar el reporter.

**Comment by feserafim** [comment]
Solución: en el contrato, se ha agregado una nueva evidencia 'issue_duration_K05' para los 'SPU_IO_K05'.
